export const UPDATE_SLIDE_LEFT = 'UPDATE_SLIDE_LEFT'
export const UPDATE_ID = 'UPDATE_ID'
export const SET_USER = 'SET_USER'
export const SET_USERNAME = 'SET_USERNAME'
export const SET_TOKEN = 'SET_TOKEN'
export const LOGOUT = 'LOGOUT'
